### PR TITLE
feat(tags): make the TAGS env. variable optional

### LINKED ISSUE #301: Use cypress-tags as main binary
Hi!

I want to use `cypress-tags` as main binary of `cypress` because it nicely wraps the execution. I do the following in `package.json`:

```json
{
    "scripts": {
        "cypress": "cypress-tags"
    }
}
```

With that step above I can always run `yarn cypress` and it should respect `TAGS` environment variable, too. But, if I do `yarn cypress run` I get the following error:

```
const envTags = found.replace(/.*=/, "");
                      ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/d/Programme/VSCode Workspace/wp-reactjs-starter/node_modules/cypress-cucumber-preprocessor/cypress-tags.js:34:23)
```

The implementation does not allow optional `TAGS`:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/152ccdd8952abbf0bcc33c108d12305f83e9fd99/cypress-tags.js#L32

Would it be possible to make it optional, too, like `GLOB`?

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/152ccdd8952abbf0bcc33c108d12305f83e9fd99/cypress-tags.js#L20-L26

Regards,
Matthew 🙂

### PR DESCRIPTION
**Pull request by vladonemo**
Fixes #301

### CODE REVIEW

**Comment by matzeeable** [comment]
Thanks for the implementation. When will this be merged? 🙂

**Comment by lgandecki** [comment]
Good call. I haven't had a chance to try this out. Should be over the weekend or early next week.

**Comment by lgandecki** [comment]
Thanks @vladonemo and @matzeeable  :) Sorry for the delay. Please let me know if it works the way you wanted @matzeeable

**Pull request merged**
