### PR TITLE
fix(nonGlobalStepDefinitions): .features files now work with webpack

### PR DESCRIPTION
**Pull request by sebastiandero**
I have tried with our project (80+ scenarios) they now seem to work.

tests in the repo also pass (some dont because of windows vs linux path slashes, but that was the case before)

#304

### CODE REVIEW

**Comment by badeball** [comment]
It seems like this conditionally removes the cache busting in case Weback is detected. The cache busting is however important and serves a particular purposes when using `nonGlobalStepDefinitions: true`. Are you using it with `true` or `false`?

**Comment by sebastiandero** [comment]
@badeball 
```{
    "stepDefinitions": "src/integration",
    "nonGlobalStepDefinitions": true
}```

this is what i tested with

**Comment by sebastiandero** [comment]
@badeball i've just encountered some weird behavior, let me have another look

**Comment by sebastiandero** [comment]
@badeball if you could do another review, that would be awesome, im now deleting the moduleid entry from require.cache

**Comment by badeball** [comment]
The current state of things is indeed how I imagined it would be. Did it solve the problem you mentioned above?

**Comment by sebastiandero** [comment]
@badeball yes it did, now tests run as expected.

**Comment by lgandecki** [comment]
Thanks so much for the PR @sebastiandero , glad you got it. 
Also, thanks @badeball for a spot on review :-)

**Pull request merged**
