### PR TITLE
Fix lodash security vulnerability

### PR DESCRIPTION
**Pull request by roschaefer**
See: https://github.com/lodash/lodash/pull/4336

### CODE REVIEW

**Comment by roschaefer** [comment]
Actually, I'm not quite sure if that really fixes the security vulnerability. When I `yarn why lodash` in [our package.json](https://github.com/Human-Connection/Human-Connection/blob/master/package.json) then I see all the references to this package. But when I `npm ls lodash` in a local copy of this repo on my machine, I see a lot of dependencies that rely on `lodash` < `v4.17.13`. Could sb. double-check?

Also did you consider to use a service like [dependabot](https://dependabot.com/)?

**Comment by lgandecki** [comment]
This is a testing tool, that doesn't get deployed to production, so the risks are small, the stability of results across the board for existing users are much more important.
Take a look here for example for a voice "from the other side":

https://twitter.com/dan_abramov/status/1149795048722067456

**Comment by lgandecki** [comment]
Hello, I just merged in a similar change (But preferred to update the package-lock json myself, to minimize changes the next time I will be changing dependencies), I tried to add you as a coauthor using the instruction from here: https://help.github.com/en/articles/creating-a-commit-with-multiple-authors , as you can see in this commit: 
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/commit/270106e0ff08ca8bd3885bfde83f5f5a481f61eb

 but it didn't work :( Anyway, I hope that helps!

**Comment by roschaefer** [comment]
It's very sweet that you considered to add me as a co-author :heart: but if that didn't work I don't mind. I checked our repository and it seems that we're not using any outdated version of lodash anymore, at least not because of `cypress-cucumber-preprocessor`.

```
robert@e480 ~/D/h/Human-Connection> yarn info lodash version
yarn info v1.17.3
4.17.15
Done in 0.27s.
robert@e480 ~/D/h/Human-Connection> yarn why lodash
yarn why v1.17.3
[1/4] Why do we have the module "lodash"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "lodash@4.17.15"
info Reasons this module exists
   - "cypress" depends on it
   - Hoisted from "cypress#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#cucumber#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#core#lodash"
   - Hoisted from "cypress#getos#async#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#core#@babel#generator#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#preset-env#@babel#plugin-transform-block-scoping#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#core#@babel#traverse#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#core#@babel#types#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#preset-env#@babel#plugin-transform-modules-amd#@babel#helper-module-transforms#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#preset-env#@babel#plugin-proposal-unicode-property-regex#@babel#helper-regex#lodash"
   - Hoisted from "cypress-cucumber-preprocessor#@cypress#browserify-preprocessor#@babel#preset-env#@babel#plugin-transform-classes#@babel#helper-define-map#lodash"
info Disk size without dependencies: "4.86MB"
info Disk size with unique dependencies: "4.86MB"
info Disk size with transitive dependencies: "4.86MB"
info Number of shared dependencies: 0
Done in 0.51s.
robert@e480 ~/D/h/Human-Connection> yarn list lodash
yarn list v1.17.3
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ lodash@4.17.15
Done in 0.46s.
```

So this can be closed :+1:

**Pull request closed without merging**
