### PR TITLE
feat(step_definition): Add option to define path for the common folder

### PR DESCRIPTION
**Pull request by EmmanuelDemey**
#136

### CODE REVIEW

**Comment by lgandecki** [comment]
Cool. I like your approach, with tests and all. Looks like we need to fill the missing parts of the documentation still before we can merge it, so we don't release with a confusing doc. 
Do you want to take a stab at filling it in? Don't stress it too much - we will merge it with whatever you propose (as long as it's not technically incorrect ;-) ), and we will tweak it later if needed be.

**Comment by lgandecki** [comment]
cool, thank you so much!

**Comment by EmmanuelDemey** [comment]
I have to difficulty to define the goal of the `nonGlobalStepDefinitions` option. Do you have an idea ?

**Comment by lgandecki** [comment]
It's the difference between using the Cypress Cucumber Preprocessor Style pattern for placing step definitions files, and the "oldschool" (everything is global) Cucumber style

**Comment by EmmanuelDemey** [comment]
updated

**Pull request merged**
