### PR TITLE
Added use of @ignore tag

### PR DESCRIPTION
**Pull request by GlynnJKW**
I often use the @ignore tag as a way to comment out full scenarios/examples that aren't currently working in my tests, so I thought it would be useful to have in this project as well.

### CODE REVIEW

**Comment by dankelleher** [comment]
+1 for this feature! Also a @focus or @only tag would be nice, to run only the features that are currently being worked on.

**Comment by marceloogeda** [comment]
This will be so helpful

**Comment by lgandecki** [comment]
Fixed in 1.6.0 #100 - Thank you guys for all the support!

**Comment by anshupitlia** [comment]
Hey, is the @ignore tag working? or is there any way to write cypress run --env TAGS='~@ignore'?

**Pull request closed without merging**
