### PR TITLE
bump chokidar from 2.1.8 to 3.5.1

### PR DESCRIPTION
**Pull request by NyanHorse**
Bump chokidar from 2.1.8 to 3.5.1 due to a vulnerability in its transient dependency glob-parent (fixed in version 5.1.2)

### CODE REVIEW

**Comment by paulblyth** [comment]
@lgandecki would you be able to merge this? It would help cleaning up some of our security alerts 🙏 thanks!

**Review by paulblyth — COMMENTED** [review]
Looking at the [chokidar changelog](https://github.com/paulmillr/chokidar#changelog) the only breaking change was the bump in node version (to 8.16), I think this project uses 12 and the build passes so the bump in the major version should be safe enough.

**Comment by lgandecki** [comment]
sure, thanks for checking

**Comment by paulblyth** [comment]
Thank you @lgandecki 🙌 

It looks like the merge commit didn't trigger a release (semantic release didn't think it needed one), are you able to manually publish?

**Comment by lgandecki** [comment]
ah, yes, since somehow the commit didn't follow the required format.. I will do the bump in a sec

**Pull request merged**
