### PR TITLE
Fix running tags on Windows

### PR DESCRIPTION
**Pull request by nickdunn**

### CODE REVIEW

**Comment by lgandecki** [comment]
@nickdunn  cool, thanks! I don't have windows handy to verify, but I trust you did and it works, right? :)

**Comment by lgandecki** [comment]
I see the linting fails - could you please run npm run fixStyle  and push?

**Comment by nickdunn** [comment]
This morning I've been working through trying to get this running in Jenkins on a Windows box and we isolated it down to this issue. Our build is now building/passing using my fork, so I'm comfortable that this fix works :-)

**Comment by nickdunn** [comment]
How soon do you think a new version could be pushed out to npm?

**Comment by lgandecki** [comment]
shoot, it should happen automatically but I forgot to add a fix: prefix to the commit message

**Comment by lgandecki** [comment]
I will merge this one https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/176/files and it will release a new version with both changes, I need up to an hour

**Comment by nickdunn** [comment]
Brilliant, thank you! I'll keep looking out for it.

**Pull request merged**
