### PR TITLE
Fix output path for bundle directory on windows platform

### PR DESCRIPTION
**Pull request by agentHoover**
Code fix for splitting paths on windows platform. 

Added work-space settings for eslint to override arrow function parenthesis and single quotes. 

cypress/index.js line ending were failing the eslint check.
Added eslint ignore to that one file for line-endings.

Added .gitattributes file to keep posix line endings on windows.

### CODE REVIEW

**Comment by lgandecki** [comment]
Thank you for your help @agentHoover !

I'm a bit itchy about adding all these extra things to the project - I don't see them in other open source libraries, could you explain a bit why do you think this package requires an extra treatment like that?

I'm a bit afraid about decreasing the signal to noise ratio. It's already not very good

**Comment by agentHoover** [comment]
Yeah,  I debated long and hard about how to handle that.  The short answer is _those configuration changes were things I had to do just to get the project green on a windows machine_ with visual studio code.  Anyone trying to develop on this project on a windows machine is going to have the same issues and I figured I would just save them the 1 1/2 hours it took me to figure out why building was failing on a clean repo. Here are details of why each change was necessary. 

.gitattributes file --> On windows the default setting for git is to replace all line endings on checkout with the standard windows line endings `crlf`.  The eslint settings for this project are validating that all line endings are standard unix line endings `lf` and this was causing the build to fail on my machine. The .gitattribute file is just a way to tell git that for this project... preserve the unix `lf` line endings on checkout.  It has zero material impact to the functionality of the code.  **The other choice here** would be to tell eslint to ignore the line endings and let git manage this for you.  It will convert them back to lf on push automatically. But I was trying to not to change eslint configuration for the project as a whole. 

index.js -->  related to the line ending issue. Not sure if the file itself was checked in with crlf line endings or what but eslint was failing on this file even after I added the .gitattribute file and rechecked out the project.  The ignore just tells eslint to not care about it for that one file.  **The other option** here would be to modify the line endings in the file to be `lf` and commit that.  I can do that if you prefer.

.vscode/settings.json -->  this is specific to vscode and just overrides global eslint configurations I have for my day job to make the match what this project requires..  Probably, this should not be included and the file should be added to .git ignore instead. 

Let me know how you want to handle these and I will gladly accomodate it.

**Comment by mhodgson** [comment]
Just wanted to chime in here. The windows developers on our team both had issues that were solved specifically by the `path.sep` fix in this PR. If we could get that part merged in I think it would fix a real world issue that devs are having. It took us a very long time to track down.

**Comment by lgandecki** [comment]
@mhodgson thanks for chimming in. I was slacking this because of the other files, and also lack of time for this project.

@agentHoover Thanks again for the work and sorry for the delay. Addressing your comments:

```
index.js --> related to the line ending issue. Not sure if the file itself was checked in with crlf line endings or what but eslint was failing on this file even after I added the .gitattribute file and rechecked out the project. The ignore just tells eslint to not care about it for that one file. The other option here would be to modify the line endings in the file to be lf and commit that. I can do that if you prefer.
```

Please change the endings in the file and don't introduce the eslint ignore.

```
.vscode/settings.json --> this is specific to vscode and just overrides global eslint configurations I have for my day job to make them match what this project requires.. Probably, this should not be included and the file should be added to .git ignore instead.
```

Yeah I think that would be better :-)

Thanks!

The moment you get these two in I will merge. Please tag me here as well to make sure I get a direct email from github.

**Comment by agentHoover** [comment]
@lgandecki .  No problem.  I would not have had time to address it before today anyway. :).  I have made the changes you requested.

**Comment by lgandecki** [comment]
Looks like tests passed, I'm going to merge, and release soon, thanks!

**Pull request merged**
