### PR TITLE
Included And keywords in resolveStepDefinition

### PR DESCRIPTION
**Pull request by tamoore**
- Updated the ScenarioOutline to have an instance of the And keyword
- The logic around the `latestType` seemed redundant so I removed it.

🍻 for the module.

### CODE REVIEW

**Comment by lgandecki** [comment]
Thank you for the PR!
But unfortunately that's not how it's supposed to work :-(

And shouldn't be defined separately. Actually, what should be happening is:

It shouldn't matter whether you define your step with
given() when() or then(), they will be treated the same way and should be matched with .feature Given/When/Then/And.

In other words, in Scenario Outline you should be able to use "and" instead of "when" - as you did, but you shouldn't have to change when to and in cypress/support/step_definitions/scenario_outline_string.js for it to work. Does it make sense?

**Comment by tamoore** [comment]
Sorry I wasn't 100% clear on that.

My understanding of your comment is that you should be able to use 'And' in .feature file and it will match any step definition regardless of whether it's defined as a `when`, `then` or `given`?

**Comment by lgandecki** [comment]
Yes. Take a look here
https://cucumber.io/docs/reference#scenario-outline

In particular:
Steps
A step typically starts with Given, When or Then. If there are multiple Given or When steps underneath each other, you can use And or But. Cucumber does not differentiate between the keywords, but choosing the right one is important for the readability of the scenario as a whole.

And

Cucumber does not differentiate between the five step keywords Given, When, Then, And and But.

**Comment by tamoore** [comment]
Closing as per discussion.

**Pull request closed without merging**
