### PR TITLE
fix(featuresloader): make bundling feature work with repeated non-glo…

### LINKED ISSUE #230: cypress-cucumber-example not working with bundled features
Seems bundled features breaks step resolution where there is more than one instance of a matching step 

**Steps to reproduce:**

Updated the cypress-cucumber-example project to include 
cypress-cucumber-preprocessor: ^1.15.1

Added All.features file to cypress/integration folder

npx cypress run --spec cypress/integration/All.features 

````
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.3.0                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      1 found (All.features)                                                             │
  │ Searched:   cypress/integration/All.features                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: All.features...                                                                 (1 of 1) 


  The Google
    ✓ Opening a Google network page (1128ms)
    ✓ Different kind of opening (3074ms)

  The Facebook
    ✓ Opening a social network page (2442ms)
    1) Different kind of opening

  The Twitter
    ✓ Opening Twitter (3343ms)
    ✓ Opening Twitter again (3009ms)


  5 passing (32s)
  1 failing

  1) The Facebook Different kind of opening:
     CypressError: Timed out retrying: expected 'Facebook – log in or sign up' to include 'Google'
      at Object.cypressErr (https://www.facebook.com/__cypress/runner/cypress_runner.js:83139:11)
      at Object.throwErr (https://www.facebook.com/__cypress/runner/cypress_runner.js:83104:18)
      at Object.throwErrByPath (https://www.facebook.com/__cypress/runner/cypress_runner.js:83131:17)
      at retry (https://www.facebook.com/__cypress/runner/cypress_runner.js:76579:16)
      at https://www.facebook.com/__cypress/runner/cypress_runner.js:68565:18
      at tryCatcher (https://www.facebook.com/__cypress/runner/cypress_runner.js:132036:23)
      at Promise._settlePromiseFromHandler (https://www.facebook.com/__cypress/runner/cypress_runner.js:130054:31)
      at Promise._settlePromise (https://www.facebook.com/__cypress/runner/cypress_runner.js:130111:18)
      at Promise._settlePromise0 (https://www.facebook.com/__cypress/runner/cypress_runner.js:130156:10)
      at Promise._settlePromises (https://www.facebook.com/__cypress/runner/cypress_runner.js:130231:18)
      at Async._drainQueue (https://www.facebook.com/__cypress/runner/cypress_runner.js:126960:16)
      at Async._drainQueues (https://www.facebook.com/__cypress/runner/cypress_runner.js:126970:10)
      at Async.drainQueues (https://www.facebook.com/__cypress/runner/cypress_runner.js:126844:14)
      at <anonymous>




  (Results)

  ┌────────────────────────────┐
  │ Tests:        6            │
  │ Passing:      5            │
  │ Failing:      1            │
  │ Pending:      0            │
  │ Skipped:      0            │
  │ Screenshots:  1            │
  │ Video:        true         │
  │ Duration:     32 seconds   │
  │ Spec Ran:     All.features │
  └────────────────────────────┘


  (Screenshots)

  - /Users/jcundill/code/cypress-cucumber-example/cypress/screenshots/All.features/The Facebook -- Different kind of opening (failed).png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/jcundill/code/cypress-cucumber-example/cypress/videos/All.features.mp4 (6 seconds)


====================================================================================================

  (Run Finished)


      Spec                                                Tests  Passing  Failing  Pending  Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖ All.features                              00:32        6        5        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)                        00:32        6        5        1        -        -  

````

### PR DESCRIPTION
**Pull request by lgandecki**
…bal steps

fix #230

### CODE REVIEW

**Comment by lgandecki** [comment]
wanna take a look @jcundill ?
It's kinda ugly.. but not sure how else to approach this problem

**Comment by jcundill** [comment]
@lgandecki it's not that ugly 😄, however there still seems to be issues around hooks.

In the example project, I changed `cypress/integration/google/different.js` to be

````javascript
import { Given, Then, Before } from "cypress-cucumber-preprocessor/steps";

const url = "https://google.com";

let myBeforeCount = 0;

Before(() => {
  expect(myBeforeCount).to.be.lessThan(2);
  myBeforeCount += 1;
})

Given(`I kinda open Google page`, () => {
  cy.visit(url);
});

// This is the same step that we have in socialNetworks/Facebook/different.js, but you don't have to worry about collisions!
Then(`I am very happy`, () => {
  cy.title().should("include", "Google");
});

````
So you'd expect the Before hook to just get called twice - once for each scenario in the Google.feature.

However when I tried it I got 

````
Cudas-MBP:cypress-cucumber-example jcundill$ npx cypress run --spec "**/*.features"

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.4.1                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      1 found (All.features)                                                             │
  │ Searched:   **/*.features                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: All.features...                                                                 (1 of 1)


  The Google
    ✓ Opening a Google network page (2721ms)
    ✓ Different kind of opening (4399ms)

  The Facebook
    1) Opening a social network page
    2) Different kind of opening

  The Twitter
    3) Opening Twitter
    4) Opening Twitter again


  2 passing (30s)
  4 failing

  1) The Facebook Opening a social network page:
     AssertionError: expected 2 to be below 2
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Object.gotValue (https://www.google.com/__cypress/runner/cypress_runner.js:118104:18)
      at Object.gotAccum (https://www.google.com/__cypress/runner/cypress_runner.js:118093:25)
      at Object.tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (https://www.google.com/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (https://www.google.com/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromiseCtx (https://www.google.com/__cypress/runner/cypress_runner.js:116992:10)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://www.google.com/__cypress/runner/cypress_runner.js:113692:12)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>

  2) The Facebook Different kind of opening:
     AssertionError: expected 2 to be below 2
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Object.gotValue (https://www.google.com/__cypress/runner/cypress_runner.js:118104:18)
      at Object.gotAccum (https://www.google.com/__cypress/runner/cypress_runner.js:118093:25)
      at Object.tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (https://www.google.com/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (https://www.google.com/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromiseCtx (https://www.google.com/__cypress/runner/cypress_runner.js:116992:10)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://www.google.com/__cypress/runner/cypress_runner.js:113692:12)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>

  3) The Twitter Opening Twitter:
     AssertionError: expected 2 to be below 2
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Object.gotValue (https://www.google.com/__cypress/runner/cypress_runner.js:118104:18)
      at Object.gotAccum (https://www.google.com/__cypress/runner/cypress_runner.js:118093:25)
      at Object.tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (https://www.google.com/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (https://www.google.com/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromiseCtx (https://www.google.com/__cypress/runner/cypress_runner.js:116992:10)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://www.google.com/__cypress/runner/cypress_runner.js:113692:12)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>

  4) The Twitter Opening Twitter again:
     AssertionError: expected 2 to be below 2
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Object.gotValue (https://www.google.com/__cypress/runner/cypress_runner.js:118104:18)
      at Object.gotAccum (https://www.google.com/__cypress/runner/cypress_runner.js:118093:25)
      at Object.tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (https://www.google.com/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (https://www.google.com/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromiseCtx (https://www.google.com/__cypress/runner/cypress_runner.js:116992:10)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://www.google.com/__cypress/runner/cypress_runner.js:113692:12)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>




  (Results)

  ┌────────────────────────────┐
  │ Tests:        6            │
  │ Passing:      2            │
  │ Failing:      4            │
  │ Pending:      0            │
  │ Skipped:      0            │
  │ Screenshots:  4            │
  │ Video:        true         │
  │ Duration:     30 seconds   │
  │ Spec Ran:     All.features │
  └────────────────────────────┘


  (Screenshots)

  - /Users/jcundill/code/cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/screenshots/All.features/The Facebook -- Opening a social network page (failed).png (1280x720)
  - /Users/jcundill/code/cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/screenshots/All.features/The Facebook -- Different kind of opening (failed).png (1280x720)
  - /Users/jcundill/code/cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/screenshots/All.features/The Twitter -- Opening Twitter (failed).png (1280x720)
  - /Users/jcundill/code/cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/screenshots/All.features/The Twitter -- Opening Twitter again (failed).png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/jcundill/code/cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/videos/All.features.mp4 (6 seconds)


====================================================================================================

  (Run Finished)


      Spec                                                Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖ All.features                              00:30        6        2        4        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)                        00:30        6        2        4        -        -

````

Seems the Before hook is getting triggered on every scenario still

**Comment by lgandecki** [comment]
Yup, similar work has to be done for hooks. I was thinking of getting this in to partially fix the problem but I guess its better to have it all either working or not working with non global steps definitions. Should have time to get back to this by the end of the week

**Comment by lgandecki** [comment]
@jcundill I've made it work with hooks, it was rather trivial - following the same pattern, but for some reason I couldn't find time to sit down to this over the last month. Not sure if you are still interested in this project and if you would like to add some more feedback - if I don't hear from you in the next few days I will merge this in :)

**Pull request merged**
