### PR TITLE
Add support for Cucumber Html Reporter (issue #155)

### PR DESCRIPTION
**Pull request by jcundill**
PR to add cucumber.json file generation to the project, addresses issue https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/155

Screenshot 2019-07-10 at 16 58 42

These cucumber.json files can then be used to display cypress cucumber tests in standard cucumber reporting tools

Screenshot 2019-07-10 at 16 57 18

Screenshot 2019-07-10 at 16 58 04

### CODE REVIEW

**Comment by lgandecki** [comment]
wow! Thanks so much for this! It would be a great feature to have! I will spend a few hours next week to understand the changes.

**Comment by hieutrandn9889** [comment]
How to generate this cucumber report?
please help me to create the report

**Comment by lgandecki** [comment]
@hieutrandn9889 this is a PR that will allow this functionality. If you are not here to help review and merge the code please wait patiently. PRs in general are not a place to ask for support or help :) 
You could also checkout the fork and use it meanwhile, but seeing you asking this question in the first place I wouldn't recommend that - this will be in soon enough for you to use without jumping through extra hoops, that later might be difficult to jump back from.

**Comment by mzambrini** [comment]
Any news?

**Comment by smalot** [comment]
Nice job, really impressed !
Any news ?

**Comment by lgandecki** [comment]
Sorry for the delay guys, as you can see this is a large PR and I want to respect the work by reviewing it thoroughly. I'm currently on mini-vacation, and didn't get around testing it before leaving. Seeing how much you need it decided to release a quick beta. For now, if you want to play around with/test/start using early this functionality do:

``` npm install --save-dev cypress-cucumber-preprocessor@1.13.0-beta ```

or change your package.json to have this entry :

``` "cypress-cucumber-preprocessor": "1.13.0-beta" ```

Some details about the code might change but I'd guess the way to use it won't, so once this is merged to master, you will be able to upgrade to 1.13.0 smoothly. 

Thanks!

**Comment by lgandecki** [comment]
This is now released as of 1.13.0 - the only change I've made was to make this report optional. 
Thanks again @jcundill ! Solid work.

**Comment by maximkoshelenko** [comment]
Hello. Is there any possibility to combine multiple .json reports into one?
Using this settings each of mine feature files create separate '.json' :
"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": true,
"cucumberJson": {
"generate": true,
"outputFolder": "cypress/reports/cucumber",
"filePrefix": "",
"fileSuffix": ".cucumber"
}
}
image

**Comment by jcundill** [comment]
@maximkoshelenko see https://stedolan.github.io/jq/

`jq -s 'map(.[0])' *.cucumber.json > combined.json`  will do that for you

**Comment by maximkoshelenko** [comment]
@jcundill thanks :)

**Comment by RoopaShivakumar** [comment]
@jcundill @maximkoshelenko @lgandecki @hieutrandn9889 @jcundill @smalot 

> PR to add cucumber.json file generation to the project, addresses issue #155
> 
> Screenshot 2019-07-10 at 16 58 42
> 
> These cucumber.json files can then be used to display cypress cucumber tests in standard cucumber reporting tools
> 
> Screenshot 2019-07-10 at 16 57 18
> 
> Screenshot 2019-07-10 at 16 58 04

Can we have this report in Cypress 10.3 and 
"@badeball/cypress-cucumber-preprocessor": "^11.4.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "cy-verify-downloads": "^0.1.8",

Have generated the report with multiple cucumber html reporter plugin but somehow cannot get the Duration time of execution
image


my package.json is as below
"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": true,
"stepDefinitions": "cypress/e2e/AdaptDemandTest/*.{js,ts}",
"cucumberJson": {
"generate": true,
"outputFolder": "cypress/cucumber-json",
"filePrefix": "",
"fileSuffix": ".cucumber"
},
"json": {
"enabled": true,
"output": "cypress/cucumber-json/log.json",
"formater": "cucumber-json-formatter.exe"
},
"messages": {
"enabled": true,
"output": "cypress/cucumber-json/messages.ndjson"
},
"filterSpecs": true,
"omitFiltered": true
},

and the js file for generating html report from json outputput file is as below
const report = require('multiple-cucumber-html-reporter');
const fs = require('fs');
/*
fs.readFile('cypress/cucumber-json/log.json', function read(err, data) {
if (err) {
throw err;
}
//console.log("Data is " + (data))
var runInfos = JSON.parse(JSON.stringify(data));
//}) */
report.generate({
jsonDir: './cypress/cucumber-json',
reportPath: './cypress/cucumber-json/cucumber-htmlreport.html',
displayDuration: true,
durationInMS: true,
displayReportTime: true,
pageTitle: 'ADAPT DEMAND AUTOMATION EXECUTION REPORT',
metadata: {
browser: {
name: 'chrome',
version: '103'
},
device: 'M2B-L-18KWT93',
platform: {
name: 'Microsoft Windows 11',
version: '20H2'
}
},
customData: {
title: 'Run info',
data: [
{ label: 'Project', value: 'Custom project' },
{ label: 'Release', value: 'R23' },
{ label: 'Cycle', value: 'B11221.34321' },
// label: 'Execution Start Time', value: new Date(runInfos.startedTestsAt).toLocaleString() },
//{ label: 'Execution Start Time', value: new Date(runInfos.startedTestsAt).toDateString() },
//{ label: 'Execution Start Time', value: new Date(runInfos.startedTestsAt).toISOString() },
{ label: 'Execution Start Time', value: 'Aug 1 2022' },
{ label: 'Execution End Time', value: 'Nov 19th 2017, 02:56 PM EST' }
//{ label: 'Execution End Time', value: new Date(runInfos.endedTestsAt).toLocaleString() }
//{ label: 'Execution End Time', value: new Date(runInfos.endedTestsAt).toISOString() }
]
}
});
//})

**Pull request closed without merging**
