### PR TITLE
feat(tags): fallback to globally installed cypress executable if does…

### LINKED ISSUE #328: cypress-tags assumes running in local mode
cypress-tags wrapper locates the cypress executable in the `../.bin/` folder. This is only valid in local mode, i.e. when both are installed locally. It won't work if the preprocessor is installed globally

### PR DESCRIPTION
**Pull request by vladonemo**
…n't exist locally

Fixes #328

### CODE REVIEW

**Comment by benjaminknauer** [comment]
I find this very useful. I did a PR myself then I saw this.
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/355

Maybe we can use the best of both PRs?

**Comment by lgandecki** [comment]
hmmm what would be a combination of both? If local cypress doesn't exist use global, but also allow for using global if local is there? What would be the use case of that? I can totally get the idea why fallbacking to global would make sense (as you explained in #355, and thanks for the explanation!). But not sure if it's worth to make the code more complex to allow for running with global if local is available. 
Could you explain your thinking @benjaminknauer ? Thanks!

**Comment by lgandecki** [comment]
meanwhile, @vladonemo could you please resolve the conflicts? :) sorry for that!

**Comment by benjaminknauer** [comment]
Your right. For the use case in #355 the implementation with fallback to global if local doesn't exist would also work. I cannot think of a use case where you want to run global cypress if a local installation exist. So I would be happy if you can merge #355 :)

**Comment by PSiemieniuk** [comment]
I tested it. It works. After the conflicts are sorted out, we merge this PR.

**Comment by vladonemo** [comment]
I'm on it ;)

**Comment by lgandecki** [comment]
Thanks!

**Pull request merged**
