### PR TITLE
Fix Cucumber usage with Code Coverage

### PR DESCRIPTION
**Pull request by edimitchel**
Hi there !

I create a PR for fixing an issue we encounter with **Cypress, React Unit Test, Code coverage and this Cypress-cucumber-preprocessor** plugin.

The change I made into this PR could appear weird but trust me, this fixes a very weird issue. I explain it below:

Before each test, [code coverage runs a coverage collect](https://github.com/cypress-io/code-coverage/blob/v3.8.1/support.js#L89-L122). The last statement which I would like to point is on the [`cy.window`](https://github.com/cypress-io/code-coverage/blob/v3.8.1/support.js#L121).

`cy.window` runs [a retry function for getting the window instance](https://github.com/cypress-io/cypress/blob/0bf7785d75f32614ac0a8debb5e4d87e2e9a3ecb/packages/driver/src/cy/commands/window.js#L97-L137).

The problem comes here, [near the retry command call](https://github.com/cypress-io/cypress/blob/0bf7785d75f32614ac0a8debb5e4d87e2e9a3ecb/packages/driver/src/cy/commands/window.js#L118-L134).
What I saw, it's Promise (from bluebird) calls a method using a global object (window?) where a lot of methods into (and all Cucumber steps methods too). _You begin to see the problem ?_

The problem is that the function called is `then`, which create a new step definition but with as expresion, two functions: `resolve `and `reject` probably coming from the Promise.

**The solution have been to rename the method `then` with the first character in uppercase.**

So, I talk about a new step definition, you can see it [in live here](https://github.com/bahmutov/cypress-react-unit-test/pull/374).

If you want more explaination, I can provide. But, to be clear, I would to integrate this change quickly.

Thanks

Edit : I have created an issue here : #427

### CODE REVIEW

**Comment by lgandecki** [comment]
I see. Thanks for the investigation and PR.

In this case we would need to remove all the globals that start with lowercase letters. It makes no sense to have given/when but not then. 

We should only support Given/When/Then from this change and it will be released as a breaking change, so people will be able to update easily.

Are you willing to work on this a bit more?

**Comment by edimitchel** [comment]
Yes I can do more and remove all lowercased methods.
Should we release a new major release for avoid surprises to developers who use lowercased methods ?

**Comment by badeball** [comment]
> Should we release a new major release for avoid surprises to developers who use lowercased methods ?

That would be a prerequisite and in general I would say it's a goal to keep it to a minimum. Is there another way of solving this without breaking backwards compatibility? Can one for instance make global namespace pollution configurable instead?

**Comment by edimitchel** [comment]
You are not totally wrong @badeball but I think we could provide a more homogeneous method list with on capitalized names.

**Comment by edimitchel** [comment]
@lgandecki It's ready for review ;)

**Comment by lgandecki** [comment]
@edimitchel Thanks for your work. This is on my list for things to finalize this week.

@badeball do you, or someone you know actually uses the global functions with lowercase names? As far as I know they are not recognized by IDEs (that are tuned for Cucumber Given/When/Then), so I'd imagine not many people use them. I'd much rather just remove them in a major version and not add some extra code and configuration, especially if the cypress guys want to have some kind of a guide to do UnitTests + Cypress + Cucubmer ( https://github.com/bahmutov/cypress-react-unit-test/pull/374 ) it would be nice not to force them to use some obscure and temporary configuration. 

I could also make a codemod that would automatically rewrite the old-syntax in tests, if we see people complain.

**Comment by badeball** [comment]
@lgandecki, no, I don't know of any. Let's just go ahead.

**Comment by lgandecki** [comment]
Cool @badeball 
Thanks for all the work @edimitchel ! I merged it from a separate PR, because I wanted to make sure we release a major not a minor version

**Comment by grethermendezgomez** [comment]
Hello, good afternoon, I have done everything indicated and I cannot get the code coverage, any idea that may be happening. Maybe a code coverage guide using cypress cucumber? Thanks for the help

package.json
image

my files
image
image
image

test
image


any idea please?

**Pull request closed without merging**
