### PR TITLE
feature (get-cypress-config): allow check if cypress were run using --config-file option and use the configured path for get cypress config

### PR DESCRIPTION
**Pull request by gpincheiraa**
When Cypress it's running when the `--config-file` flag, the preprocessor cannot find the path configured by this flag because in `lib/stepDefinitionPath.js` the `cypress.json` always loaded from the appRoot.

### CODE REVIEW

**Comment by lgandecki** [comment]
Cool stuff, I will play around with it a little and leave a review or merge :) Thanks!

**Comment by gpincheiraa** [comment]
@lgandecki I will push the test suite for the file `stepDefinitionPath` in a few hours.

**Comment by lgandecki** [comment]
nice! I was wondering whether I should be pushing you to add tests - I'd definitely be more comfortable with keeping the high test coverage, but I realize that part is not the easiest to test and will require mocking (so not very high confidence after all). But if you are comfortable writing tests around that area that would definitely be appreciated.

**Comment by gpincheiraa** [comment]
> nice! I was wondering whether I should be pushing you to add tests - I'd definitely be more comfortable with keeping the high test coverage, but I realize that part is not the easiest to test and will require mocking (so not very high confidence after all). But if you are comfortable writing tests around that area that would definitely be appreciated.

it's ready!!!! https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/e8fee51d1c2e35fe2ba715c1ac1abccc593b7daf/lib/stepDefinitionPath.test.js

**Comment by gpincheiraa** [comment]
@lgandecki Hi! any news about this PR?

**Comment by lgandecki** [comment]
This looks all good, I'll tweak a few things, and fix a few typos, I think it's time to remove the use of fileServerFolder but I will do it in a separate PR. Thanks again.

**Comment by gpincheiraa** [comment]
Cool. The new version will be published after merge in master?

**Comment by lgandecki** [comment]
it should have, but I didn't notice that you've made the commit with feature prefix, instead of feat - so semantic ui didn't consider this PR a change that requires a publish :). After this goes through - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/281 there should be a new release with both changes though

**Comment by gpincheiraa** [comment]
> it should have, but I didn't notice that you've made the commit with feature prefix, instead of feat - so semantic release didn't consider this PR a change that requires a publish :). ( https://circleci.com/gh/TheBrainFamily/cypress-cucumber-preprocessor/289 ) After this goes through - #281 there should be a new release with both changes though

Thanks!

**Comment by mihai-iotic** [comment]
The `await cypressExecutionInstance.load()` introduced in this PR increases the start time of tests from about 1-2 seconds to about 30 seconds.

The debug log contains a few entries likes this one:
```
  cypress:server:project get project status for client id undefined at path ... +10s
  cypress:server:project no project id +2ms
```

**Pull request merged**
