### PR TITLE
fix(createtestfromscenario.js): after hook is not being called if one…

### PR DESCRIPTION
**Pull request by khaydushki**
We need the After method to be executed even if the one the steps failed.

The problem with using Before to clear the state is that our application has a lot of complexity, relations between entities etc. Our environments are even deployed pre-populated in order to execute tests as our applications is on top of three other really complex ones.

This is the suggested PR from the ongoing discussion in this issue https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/398

After hook is executed when the scenario fails.

### CODE REVIEW

**Comment by badeball** [comment]
What happens now if an after-hook fails? Will it create recursion? Can you even issue Cypress commands in a fail-handler like that?

These are question I don't want to answer. I think the safest bet is to implement both hooks using Cypress' existing hooks, thus making them share semantics. I also think this is the least surprising behavior to the user.

I made an attempt in my fork with https://github.com/badeball/cypress-cucumber-preprocessor/commit/748d55db70a4bf1dc313da2383a6f9fbac44020b and this is how I think you should do it here as well.

**Comment by khaydushki** [comment]
The Cypress after hook is implemented as suggested by @badeball for the execution of resolveAndRunAfterHooks. This way the after hook will be executed even if the step fails.

**Comment by MateuszNowosad** [comment]
The provided solution seems to work properly and it is an improvement over the previous version of this PR however, we wound up in a situation where after and before hooks are implemented differently and this could lead to confusing problems. Maybe this could be introduced as a partial solution if this feature is in high demand right now and improved upon later. In my opinion, it would be best to revisit #195, from what I can see badeball@748d55d is close to the most comprehensive solution.

@badeball I've looked through your commit and I wanted to ask a question: What's the reason that After/Before and afterEach/beforeEach should share semantics? From what I gathered from your commit message it seems like it has something to do with running them on failed tests, but I believe that both Cypress and Cucumber run After hooks on test fail. I'm struggling to make that out from your code.

**Comment by MateuszNowosad** [comment]
> My impression is that it is your desire for After-hooks to run regardsless of whether a test pass. I implemented exactly that in badeball@748d55d.

That's right, I will try to make myself more clear. In features/hooks_ordering.feature you wrote that

> where the order of exection defines order among beforeEach / Before and afterEach / After.

and then you make a feature file where 
```
Before(function() {
        assert.equal(counter++, 0, "Expected Before() to be called before beforeEach()")
      })
      beforeEach(function() {
        assert.equal(counter++, 1, "Expected beforeEach() to be called after before()")
      })
      Before(function() {
        assert.equal(counter++, 2, "Expected Before() to also be called after beforeEach()")
      })
```
That pointed me to think that in your solution there is currently Before and beforeEach behave differently than in natively in Cypress. If you were to run something like
```
describe('Example', () => {
    before(function () {
        console.log(`1`);
    })
    beforeEach(function () {
        console.log(`2`);
    })
    before(function () {
        console.log(`3`);
    })
    it('Does not do much!', () => {
        console.log(`4`);
        expect(true).to.equal(true)
    })
    after(function () {
        console.log(`5`);
    })
})
```

You would get 1,3,2,4,5 which means that the two Before's ran before beforeEach despite their order which is in contradiction with what your feature file states. This happens because of the way you use beforeEach and afterEach methods.

So now I wanted to know what's the reason for this decision since this was intentional.

**Comment by badeball** [comment]
Alright, I think I understand. Let me just make something perfectly clear to begin with: when we're mixing Cucumber and Cypress, there's rarely a single, objectively best way to do anything. My personal desire is for the preprocessor to introduce the least amount of surprises from someone *already familiar with Cucumber* and is now trying Cypress. Furthermore, *nothing* in the preprocessor is *actually* Cucumber. Everything is a re-implementation.

The `Before()` hook in Cucumber  runs before *each* test. The `before()` hook in Cypress runs *once* before all tests.

What's the best way to implement `Before()` in a cypress preprocessor? In my opinion the least surprising behavior is for it to remain running before each test, despite sharing a fairly similar name to Cypress' `before()`.

This is how it behaves in TheBrainFamily implementation and I haven't actually changed that.

**Comment by badeball** [comment]
If you have doubts or disagreements about the behavior that I implemented, then share an example where you think the behavior is wrong in addition to your desire, because frankly I think any other way of talking about this fallible.

**Comment by MateuszNowosad** [comment]
I see now. I agree with your reasoning. Are you planning on making a PR from this commit, or is there something still holding it back?

**Comment by badeball** [comment]
I am not planning on doing that. Since I'm not actually consuming this implementation myself anymore (I use my fork), I'm hesitant in making any code contributions.

**Comment by juanmendes** [comment]
@lgandecki I've verified this change with the following scenarios:

## Before change
* An `After({tags; ''})` that is tagged **does not get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`;
* An `After()` that is not tagged **does not get called** if an error occurs while running a step,  whether it's a failed assertion or just a `throw "Some error"`

## After Change
### Errors in steps
* An `After({tags; ''})` that is tagged **does get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`;
* An `After()` that is not tagged **does get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`;
* Multiple `After()` and `After({tags:''})` **do get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`

### Errors in background
* An `After({tags; ''})` that is tagged **does get** called if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`;
* An `After()` that is not tagged **does get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`;
* Multiple `After()` and `After({tags:''})` **do get called** if an error occurs while running a step, whether it's a failed assertion or just a `throw "Some error"`

### Errors in `After` implementation
* If an error occurs in the `After` (some JS error, I don't expect anyone to be running assertion within an After), **execution of current suite is halted**, which seems like a fine behavior.
image

@khaydushki It would be great if we could include these scenarios as part of the tests within this project, is that possible?

**Comment by lgandecki** [comment]
Great review, thank you. So to sum up, in case I misunderstood something, do you think the functionality is correct and fine to be merged?

**Comment by juanmendes** [comment]
> Great review, thank you. So to sum up, in case I misunderstood something, do you think the functionality is correct and fine to be merged?

I am suggesting that the change itself works in all the scenarios I could think of, but that it should have some tests to avoid regressions. I have contacted @khaydushki (we work on the same team) and either he or I will write some tests to prevent regressions.  I'm hoping to have those written by next week, if Krum doesn't have the time (we're close to a release), I will write them myself.

I suppose we could merge the changes and then merge tests but I'm afraid tests may never be written if we merge this now 😃

**Comment by lgandecki** [comment]
If you are fine with waiting a bit more for the additional test cases I'm definitely for it as well :)

**Comment by juanmendes** [comment]
@lgandecki I wrote some tests and now have a conundrum. The tests are failing because... well, I need a step to fail 😛 . I'm not sure if there's a way to specify that a step is expected to fail?

```
  ● Before and After › With tagged After part 1

    Error executing step: I executed step causing error

      83 |   flagSetByUntaggedAfterWithError = false;
      84 |   flagSetByTaggedAfterWithError = false;
    > 85 |   throw new Error("Error executing step: I executed step causing error");
         |         ^
      86 | });
      87 | 
      88 | Then(/^Error flag should be set by untagged After$/, () => {
```

The tests are proving that it's working since I added 4 steps, and the two assertions are passing

```
Test Suites: 1 failed, 6 passed, 7 total
Tests:       2 failed, 70 passed, 72 total
```


Any suggestions?

**Comment by MateuszNowosad** [comment]
Since we already have [BailOnStepFailure.feature](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/e7c08048f32f74d4884bc7f582a9deb9405f5457/cypress/integration/BailOnStepFailure.feature) where there is a similar problem maybe this could be treated the same. Comment out tests that cause an intentional fail and we can run them once in a while when things around that piece of code change. Maybe @lgandecki will have a different idea.

**Comment by juanmendes** [comment]
Thanks @MateuszNowosad 

@lgandecki I think this is ready to merge if you agree with the above.

**Comment by lgandecki** [comment]
Alrighty, let's do that for now. Thanks for the work!

**Pull request merged**
